import sqlite3
conn = sqlite3.connect('mlflow.db')
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
print("Tables:", [r[0] for r in cur.fetchall()])
cur.execute("SELECT experiment_id, name FROM experiments")
print("Experiments:", cur.fetchall())
cur.execute("SELECT run_uuid, name, status FROM runs LIMIT 20")
print("Runs:", cur.fetchall())
cur.execute("SELECT COUNT(*) FROM metrics")
print("Total metrics:", cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM params")
print("Total params:", cur.fetchone()[0])
conn.close()
